function us_and_china_plot(X1, Y1, X2, Y2, X3, Y3, X4, Y4, name_X, name_Y)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3, X4, Y4)
%  X1:  vector of plot x data
%  Y1:  vector of plot y data
%  X2:  vector of plot x data
%  Y2:  vector of plot y data
%  X3:  vector of plot x data
%  Y3:  vector of plot y data
%  X4:  vector of plot x data
%  Y4:  vector of plot y data

%  Auto-generated by MATLAB on 10-Mar-2023 20:21:20

% Create figure
figure1 = figure('WindowState','fullscreen');

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.538690476190476 0.504504504504504 0.438690476190478 0.476476476476475]);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName', name_Y + ': цены (CNY)','Parent',axes1,...
    'LineWidth',1.5);

% Create ylabel
ylabel('Показатель цены (CNY)','FontName','CMU Serif');

% Create xlabel
xlabel('Дата','FontName','CMU Serif');

box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontName','CMU Serif','FontSize',26);
% Create legend
legend(axes1,'show');

% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.538690476190476 0.036036036036036 0.438690476190476 0.387387387387387]);
hold(axes2,'on');

% Create plot
plot(X2,Y2,'DisplayName', name_Y + ': доходности (%)','Parent',axes2,...
    'LineWidth',1);

% Create ylabel
ylabel('Показатель доходности (%)','FontName','CMU Serif');

% Create xlabel
xlabel('Дата','FontName','CMU Serif');

box(axes2,'on');
grid(axes2,'on');
hold(axes2,'off');
% Set the remaining axes properties
set(axes2,'FontName','CMU Serif','FontSize',26);
% Create legend
legend(axes2,'show');

% Create axes
axes3 = axes('Parent',figure1,...
    'Position',[0.0541666666666667 0.503503503503503 0.423214285714286 0.475475475475475]);
hold(axes3,'on');

% Create plot
plot(X3,Y3,'DisplayName', name_X + ': цены (USD)','Parent',axes3,'LineWidth',1.5);

% Create ylabel
ylabel('Показатель цены (USD)','FontName','CMU Serif');

% Create xlabel
xlabel('Дата','FontName','CMU Serif');

box(axes3,'on');
grid(axes3,'on');
hold(axes3,'off');
% Set the remaining axes properties
set(axes3,'FontName','CMU Serif','FontSize',26);
% Create legend
legend(axes3,'show');

% Create axes
axes4 = axes('Parent',figure1,...
    'Position',[0.0541666666666667 0.036036036036036 0.423214285714286 0.386386386386386]);
hold(axes4,'on');

% Create plot
plot(X4,Y4,'DisplayName', name_X + ': доходности (%)','Parent',axes4,'LineWidth',1);

% Create ylabel
ylabel('Показатель доходности (%)','FontName','CMU Serif');

% Create xlabel
xlabel('Дата','FontName','CMU Serif');

box(axes4,'on');
grid(axes4,'on');
hold(axes4,'off');
% Set the remaining axes properties
set(axes4,'FontName','CMU Serif','FontSize',26);
% Create legend
legend(axes4,'show');

