function us_and_china_plot(X1, Y1, X2, Y2, X3, Y3, X4, Y4, name_X, name_Y)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3, X4, Y4)
%  X1:  vector of plot x data
%  Y1:  vector of plot y data
%  X2:  vector of plot x data
%  Y2:  vector of plot y data
%  X3:  vector of plot x data
%  Y3:  vector of plot y data
%  X4:  vector of plot x data
%  Y4:  vector of plot y data

%  Auto-generated by MATLAB on 11-Mar-2023 21:53:15

% Create figure
figure1 = figure('WindowState','fullscreen');

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.538690476190476 0.568568568568569 0.438690476190478 0.412412412412411]);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName', name_Y + ': prices (CNY)','Parent',axes1,'LineWidth',1.5);

% Create ylabel
ylabel('Price (CNY)','FontName','CMU Serif');

% Create xlabel
xlabel('Year','FontName','CMU Serif');

box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontName','CMU Serif','FontSize',26);
% Create legend
legend(axes1,'show');

% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.538690476190476 0.0840840840840841 0.438690476190476 0.389389389389389]);
hold(axes2,'on');

% Create plot
plot(X2,Y2,'DisplayName', name_Y + ': returns (%)','Parent',axes2,'LineWidth',1);

% Create ylabel
ylabel('Returns (%)','FontName','CMU Serif');

% Create xlabel
xlabel('Year','FontName','CMU Serif');

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[-12 11]);
box(axes2,'on');
grid(axes2,'on');
hold(axes2,'off');
% Set the remaining axes properties
set(axes2,'FontName','CMU Serif','FontSize',26);
% Create legend
legend(axes2,'show');

% Create axes
axes3 = axes('Parent',figure1,...
    'Position',[0.0541666666666667 0.568568568568569 0.423214285714286 0.410410410410409]);
hold(axes3,'on');

% Create plot
plot(X3,Y3,'DisplayName', name_X + ': prices (USD)','Parent',axes3,'LineWidth',1.5);

% Create ylabel
ylabel('Price (USD)','FontName','CMU Serif');

% Create xlabel
xlabel('Year','FontName','CMU Serif');

box(axes3,'on');
grid(axes3,'on');
hold(axes3,'off');
% Set the remaining axes properties
set(axes3,'FontName','CMU Serif','FontSize',26);
% Create legend
legend(axes3,'show');

% Create axes
axes4 = axes('Parent',figure1,...
    'Position',[0.0541666666666667 0.0830830830830831 0.423214285714286 0.39039039039039]);
hold(axes4,'on');

% Create plot
plot(X4,Y4,'DisplayName', name_X + ': returns (%)','Parent',axes4,'LineWidth',1);

% Create ylabel
ylabel('Returns (%)','FontName','CMU Serif');

% Create xlabel
xlabel('Year','FontName','CMU Serif');

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes4,[-35 40]);
box(axes4,'on');
grid(axes4,'on');
hold(axes4,'off');
% Set the remaining axes properties
set(axes4,'FontName','CMU Serif','FontSize',26);
% Create legend
legend(axes4,'show');

